[package]
name = "laboratory"
version = "0.1.0"
edition = "2024"

[lib]
name = "laboratory_core"
path = "src/lib.rs"

[features]
default = ["gui"]
gui = ["dep:eframe"]

[dependencies]
clap = { version = "4", features = ["derive"] }
quanttide-agent = "0.1.2"
eframe = { version = "0.33", optional = true }

[[bin]]
name = "lab"
path = "src/bin/lab.rs"

[[bin]]
name = "lab-gui"
path = "src/bin/lab-gui.rs"
required-features = ["gui"]
