use clap::{Parser, Subcommand, ValueEnum};
use quanttide_agent::llm::{CompleteOptions, LLM};
use quanttide_agent::Message;
use std::io::{self, Write};
use std::path::PathBuf;

#[derive(Parser)]
#[command(version, name = "product-blueprint")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    Init {
        #[arg(long, default_value = ".")]
        path: PathBuf,
        #[arg(long)]
        force: bool,
    },
    Generate { perspective: Perspective, #[arg(long)] brief: String },
    /// Check filled-in blueprint files. LLM required — reads files, sends to LLM, reports quality.
    Check {
        perspective: Option<Perspective>,
    },
}

#[derive(Clone, ValueEnum)]
enum Perspective {
    Product,
    Design,
    DesignLanguage,
    Architecture,
    All,
}

fn main() {
    let cli = Cli::parse();
    match cli.command {
        Commands::Init { path, force } => cmd_init(path.as_path(), force),
        Commands::Generate { perspective, brief } => cmd_generate(&perspective, &brief),
        Commands::Check { perspective } => cmd_check(perspective.as_ref()),
    }
}

const TEMPLATE_PRODUCT: &str = include_str!("../skills/product-blueprint/product.md");
const TEMPLATE_DESIGN: &str = include_str!("../skills/product-blueprint/design.md");
const TEMPLATE_DESIGN_LANGUAGE: &str = include_str!("../skills/product-blueprint/design-language.md");
const TEMPLATE_ARCHITECTURE: &str = include_str!("../skills/product-blueprint/architecture.md");

fn templates() -> [(&'static str, &'static str, &'static str); 4] {
    [
        ("product", "product.md", TEMPLATE_PRODUCT),
        ("design", "design.md", TEMPLATE_DESIGN),
        ("design-language", "design-language.md", TEMPLATE_DESIGN_LANGUAGE),
        ("architecture", "architecture.md", TEMPLATE_ARCHITECTURE),
    ]
}

fn template_by_perspective(p: &Perspective) -> Vec<(&'static str, &'static str, &'static str)> {
    match p {
        Perspective::All => templates().to_vec(),
        Perspective::Product => vec![templates()[0]],
        Perspective::Design => vec![templates()[1]],
        Perspective::DesignLanguage => vec![templates()[2]],
        Perspective::Architecture => vec![templates()[3]],
    }
}

// ── init ──

fn cmd_init(path: &std::path::Path, force: bool) {
    let dir = if path.as_os_str().is_empty() {
        PathBuf::from(".")
    } else {
        path.to_path_buf()
    };
    if !dir.exists() {
        eprintln!("error: directory does not exist: {}", dir.display());
        std::process::exit(1);
    }
    for (_, filename, content) in templates() {
        let dest = dir.join(filename);
        if dest.exists() && !force {
            eprint!("{} already exists. Overwrite? [y/N] ", filename);
            io::stdout().flush().unwrap();
            let mut input = String::new();
            io::stdin().read_line(&mut input).unwrap();
            if input.trim().to_lowercase() != "y" {
                println!("skipped: {}", filename);
                continue;
            }
        }
        std::fs::write(&dest, content).unwrap_or_else(|e| {
            eprintln!("error: failed to write {}: {}", dest.display(), e);
            std::process::exit(1);
        });
        println!("created: {}", dest.display());
    }
}

// ── generate ──

fn cmd_generate(perspective: &Perspective, brief: &str) {
    let dir = PathBuf::from("docs/dev");
    std::fs::create_dir_all(&dir).unwrap();
    let llm = LLM::default();
    for (name, filename, template_content) in &template_by_perspective(perspective) {
        let dest = dir.join(filename);
        if dest.exists() {
            eprint!("{} already exists. Overwrite? [y/N] ", dest.display());
            io::stdout().flush().unwrap();
            let mut input = String::new();
            io::stdin().read_line(&mut input).unwrap();
            if input.trim().to_lowercase() != "y" {
                println!("skipped: {}", dest.display());
                continue;
            }
        }
        println!("AI generating {} draft...", name);
        let sys = "你是一个资深产品专家。请根据用户提供的产品简介和模板要求，\
            撰写详细的产品蓝图文档。直接输出 Markdown 格式的文档内容，\
            保留模板中的标题结构，填充具体内容。不要输出多余的引导语。";
        let prompt = format!("产品简介：{}\n\n模板要求：\n{}", brief, template_content);
        match llm.complete(
            &[
                Message::new("system", sys),
                Message::new("user", &prompt),
            ],
            CompleteOptions::default(),
        ) {
            Ok(resp) => {
                std::fs::write(&dest, &resp.content).unwrap_or_else(|e| {
                    eprintln!("error: failed to write {}: {}", dest.display(), e);
                    std::process::exit(1);
                });
                println!("generated by AI: {}", dest.display());
            }
            Err(e) => {
                eprintln!("error: LLM generation failed for {}: {}", name, e);
            }
        }
    }
}

// ── check (LLM gateway) ──

fn cmd_check(perspective: Option<&Perspective>) {
    let p = perspective.unwrap_or(&Perspective::All);

    // 1. Read files — only send filled content + section headings as context
    let mut bundle = String::new();
    let mut has_file = false;
    for (name, filename, _tmpl) in &template_by_perspective(p) {
        let src = PathBuf::from(filename);
        if !src.exists() {
            bundle.push_str(&format!("[{}] {} — FILE NOT FOUND\n", name, filename));
            continue;
        }
        has_file = true;
        let content = std::fs::read_to_string(&src).unwrap();
        bundle.push_str(&format!("=== {} ({}) ===\n{}\n", name, filename, content));
    }

    if !has_file {
        eprintln!("error: no blueprint files found. Run `product-blueprint init` first.");
        std::process::exit(1);
    }

    // 2. LLM call
    let llm = LLM::default();
    let sys = "你是一个产品审查员。用户提交了一份 AI 生成的产品蓝图初稿及原始模板。\n\
        请对比模板和初稿，找出初稿中：\n\
        1. 逻辑矛盾或前后不一致的地方。\n\
        2. 模板要求但初稿遗漏的内容。\n\
        3. 明显不合理或需要人工确认的技术/设计选型。\n\
        请以列表形式输出审查意见，每条意见一行。";

    match llm.complete(
        &[
            Message::new("system", sys),
            Message::new("user", &format!("模板定义和填写内容如下：\n{}", bundle)),
        ],
        CompleteOptions::default(),
    ) {
        Ok(resp) => {
            let text = resp.content.trim();
            // ponytail: parse each line as JSON, print nicely
            for line in text.lines() {
                let line = line.trim();
                if line.is_empty() || line.starts_with("```") {
                    continue;
                }
                // ponytail: peel surrounding brackets if LLM wraps in array
                let cleaned = line
                    .trim_start_matches('[')
                    .trim_end_matches(']')
                    .trim_end_matches(',');
                if let Ok(val) = serde_json::from_str::<serde_json::Value>(cleaned) {
                    let perspective = val["perspective"].as_str().unwrap_or("?");
                    let section = val["section"].as_str().unwrap_or("?");
                    let quality = val["quality"].as_str().unwrap_or("?");
                    let issues = val["issues"].as_str().unwrap_or("");
                    let icon = match quality {
                        "empty" => "⬜",
                        "poor" => "🟡",
                        "adequate" => "🟢",
                        "good" => "✅",
                        _ => "❓",
                    };
                    let iss = if issues.is_empty() {
                        String::new()
                    } else {
                        format!(" — {}", issues)
                    };
                    println!("{} [{:>12}] {}{}", icon, perspective, section, iss);
                }
            }
        }
        Err(e) => {
            eprintln!("error: LLM call failed: {}", e);
        }
    }
}
